---
- name: Install Confluent 
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add APT key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com
        id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
      vars:
        ansible_python_interpreter: /usr/bin/python3

    # Updating and or upgrading APT messes with finding OpenJDK
    # This does not work consistently

    - name: Update APT
      apt:
        update_cache: 'yes'
        upgrade: 'yes'
    
    # Fails sometimes. Just keep calm and retry
    
    - name: Install Java
      apt: name='default-jdk'
      
    - name: Install NTP
      apt: name='ntp' state=present
      
    - name: Install unzip
      apt: name='unzip'
      
    - name: Copy Confluent tar
      copy:
        src: '{{ TAR_FILE }}'
        dest: /tmp/confluent.tar.gz
        
    - name: Copy JDBC Plugin
      copy:
        src: /Users/seetasomagani/distributions/confluentinc-kafka-connect-jdbc-10.0.0.zip
        dest: /tmp/confluentinc-kafka-connect-jdbc-10.0.0.zip
    
    # Not using implicit copy because https://github.com/ansible/ansible/issues/35645
    - name: Extract Confluent tar
      unarchive:
        src: /tmp/confluent.tar.gz
        dest: /opt/
        remote_src: yes
        
    - name: Ensures /usr/local/share/kafka/plugins dir exists
      file: path=/usr/local/share/kafka/plugins state=directory
        
    - name: Extract plugin zip
      unarchive:
        src: /tmp/confluentinc-kafka-connect-jdbc-10.0.0.zip
        dest: /usr/local/share/kafka/plugins/
        remote_src: yes
      
      #Avoiding this PITA for now
#    - name: Export voltdb PATH in .bashrc or /etc/environment
#      lineinfile:
#        path: /etc/environment
#        line: PATH="/opt/confluent/bin:$PATH"
        