---
- name: Setup Kafka Connect Dependencies
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add APT key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EEA14886
      vars:
        ansible_python_interpreter: /usr/bin/python3

        
    - name: Install Java
      apt: name='default-jdk'
      
    - name: Install Python2.7
      apt: name='python2.7'
      
    - name: Symlink Python2.7
      file:
        src: '/usr/bin/python2.7'
        dest: '/usr/bin/python'
        state: link        

    # Updating APT causes Java installation to fail so delaying it
    - name: Update APT
      apt:
        update_cache: 'yes'
        
    - name: Install NTP
      apt: name='ntp' state=present
      
    - name: Download Apache Kafka 
      uri:
        url: https://www.apache.org/dist/kafka/2.6.0/kafka_2.12-2.6.0.tgz
        method: GET
    
    # Not using implicit copy because https://github.com/ansible/ansible/issues/35645
    - name: Extract Apache Kafka
      unarchive:
        src: kafka_2.12-2.6.0.tgz
        dest: /opt/
        remote_src: yes
    
#    - name: Rename directory
#      command: mv /opt/voltdb-ent-9.3.2/ /opt/voltdb/
        